<?php

namespace App\Support;

/**
 * Interface copy for the public company site and the AI Staff panel, in the
 * three languages the site serves. Company facts do NOT live here — those
 * come from the database so the AI Staff and the page always agree.
 */
class SiteCopy
{
    /**
     * @return array<string, string>
     */
    public static function for(string $locale): array
    {
        return match ($locale) {
            'en' => self::english(),
            'ja' => self::japanese(),
            default => self::indonesian(),
        };
    }

    /**
     * @return array<string, string>
     */
    private static function indonesian(): array
    {
        return [
            'nav_services' => 'Layanan',
            'nav_projects' => 'Proyek',
            'nav_how' => 'Cara kerja',
            'nav_about' => 'Tentang',
            'nav_contact' => 'Kontak',
            'talk_to_staff' => 'Bicara dengan AI Staff',
            'studio_companion' => 'Partner AI untuk ide Anda',
            'studio_explore' => 'Kenali FTS lebih dekat',
            'studio_welcome' => 'Halo, saya :name.',
            'studio_chat' => 'Ruang untuk ide Anda',
            'studio_expand' => 'Perbesar percakapan',
            'hero_eyebrow' => 'Selamat datang di FTS AI Studio',
            'hero_title' => 'Ide besar dimulai',
            'hero_title_accent' => 'dari percakapan.',
            'hero_intro' => 'Kenalkan :name, partner AI Anda di FTS. Jelajahi solusi, temukan inspirasi, dan wujudkan ide untuk bisnis Anda.',
            'hero_try' => 'Coba tanyakan',
            'hero_greeting' => 'Halo! Saya :name 👋 Ada yang bisa saya bantu?',
            'hero_markets' => 'Melayani bisnis di Indonesia & Jepang',
            'q_about' => 'Apa itu FTS?',
            'q_about_msg' => 'Halo, apa itu FTS dan apa yang dikerjakan perusahaan ini?',
            'q_services' => 'Layanan apa saja?',
            'q_services_msg' => 'Layanan apa saja yang ditawarkan FTS?',
            'q_projects' => 'Lihat proyek',
            'q_projects_msg' => 'Boleh tunjukkan contoh proyek yang sudah dikerjakan FTS?',
            'q_ai_website' => 'Apa itu AI Website?',
            'q_ai_website_msg' => 'Apa itu AI Website dan apa bedanya dengan chatbot biasa?',
            'q_price' => 'Berapa biayanya?',
            'q_price_msg' => 'Berapa biaya untuk membuat AI Website?',
            'q_consult' => 'Jadwalkan konsultasi',
            'q_consult_msg' => 'Saya tertarik dan ingin konsultasi gratis.',
            'services_eyebrow' => 'Layanan',
            'services_title' => 'Teknologi yang langsung bekerja untuk bisnis Anda.',
            'services_sub' => 'Pengembangan website, AI automation, offshore development, dan AI Website — dengan standar kualitas Jepang dan pemahaman pasar Indonesia.',
            'from' => 'Mulai',
            'by_quotation' => 'Harga sesuai kebutuhan',
            'ask_about_service' => 'Tanya AI Staff',
            'ask_service_msg' => 'Ceritakan lebih detail tentang layanan :name.',
            'featured' => 'Unggulan',
            'how_eyebrow' => 'Bukan chatbot biasa',
            'how_title' => 'Staf AI yang benar-benar bekerja di dalam website.',
            'how_1_title' => 'Memahami bisnis Anda',
            'how_1_body' => 'Menjawab dari knowledge base resmi perusahaan — bukan menebak dari internet.',
            'how_2_title' => 'Menampilkan data nyata',
            'how_2_body' => 'Menunjukkan layanan, harga, foto, dan proyek langsung dari database Anda.',
            'how_3_title' => 'Menyelesaikan tugas',
            'how_3_body' => 'Mencatat permintaan konsultasi, demo, penawaran, atau reservasi untuk tim Anda.',
            'how_4_title' => 'Tahu kapan memanggil manusia',
            'how_4_body' => 'Menyerahkan percakapan ke tim Anda lengkap dengan ringkasannya.',
            'projects_eyebrow' => 'Proyek & solusi',
            'projects_title' => 'Sudah berjalan, bukan sekadar konsep.',
            'projects_sub' => 'Website, platform, dan solusi AI yang kami bangun untuk klien di Indonesia, Jepang, dan Thailand.',
            'ask_about_project' => 'Tanya tentang proyek ini',
            'ask_project_msg' => 'Ceritakan tentang proyek :name.',
            'projects_more' => 'Total :count proyek di portofolio kami — tanyakan contoh yang paling relevan untuk bisnis Anda.',
            'visit' => 'Kunjungi',
            'status_live' => 'Live',
            'status_pilot' => 'Pilot',
            'status_demo' => 'Demo',
            'status_in_development' => 'Dalam pengembangan',
            'about_eyebrow' => 'Tentang FTS',
            'process_title' => 'Cara kami bekerja',
            'faq_title' => 'Pertanyaan umum',
            'faq_more' => 'Pertanyaan lain? Tanyakan langsung ke AI Staff.',
            'cta_title' => 'Siap punya AI Staff sendiri?',
            'cta_body' => 'Ceritakan bisnis Anda. :name akan mencatat kebutuhan Anda dan tim FTS akan menghubungi Anda.',
            'cta_button' => 'Mulai konsultasi gratis',
            'footer_note' => 'Website ini dijalankan oleh AI Website buatan FTS.',
            'staff_role' => 'AI Staff · FTS',
            'staff_online' => 'Online',
            'chat_placeholder' => 'Tulis pertanyaan Anda…',
            'chat_send' => 'Kirim',
            'chat_intro' => 'Halo! Saya :name, AI Staff di FTS. Saya bisa menjelaskan layanan kami, menunjukkan proyek, atau membantu Anda memulai konsultasi. Ada yang bisa saya bantu?',
            'thinking' => ':name sedang mengetik…',
            'handed_over' => 'Tim FTS sudah diberi tahu dan akan bergabung di percakapan ini.',
            'waiting_for_staff' => 'Pesan Anda sudah diteruskan ke tim FTS. Mohon tunggu sebentar.',
            'staff_label' => 'Tim FTS',
            'view_details' => 'Lihat detail',
            'see_projects' => 'Lihat contoh proyek',
            'lead_received' => 'Permintaan diterima',
            'lead_followup' => 'Tim FTS akan segera menghubungi Anda.',
            'lead_type_consultation' => 'Konsultasi',
            'lead_type_demo' => 'Demo',
            'lead_type_quotation' => 'Penawaran harga',
            'reference' => 'No. referensi',
            'features' => 'Fitur utama',
            'pricing' => 'Harga',
            'open_menu' => 'Buka menu',
            'close' => 'Tutup',
            'new_chat' => 'Percakapan baru',
            'connection_error' => 'AI Staff belum tersambung. Muat ulang halaman untuk mencoba lagi.',
            'error_generic' => 'Maaf, AI Staff sedang tidak tersedia. Silakan coba lagi sebentar lagi.',
            'stat_projects' => 'proyek selesai',
            'stat_services' => 'layanan',
            'stat_languages' => 'bahasa',
            'stat_available' => 'AI Staff siaga',
            'stat_countries' => 'negara',
            'demo_visitor' => 'Saya punya hotel 40 kamar di Bali. Bisa bantu apa?',
            'demo_staff' => 'Tentu! Untuk hotel, AI Website bisa jadi resepsionis virtual: tamu cek kamar, harga, lalu reservasi. Ini contoh yang sudah berjalan 👇',
            'demo_card_title' => 'Hotel AI Website V1',
            'demo_card_sub' => 'Resepsionis virtual · reservasi · 3 bahasa',
            'pricing_eyebrow' => 'Harga',
            'pricing_title' => 'Harga transparan, tanpa biaya tersembunyi.',
            'pricing_sub' => 'Paket dengan harga terbuka ada di bawah. Untuk AI Website, AI automation, dan proyek khusus, harga mengikuti ruang lingkup — tanyakan ke Aya untuk penawaran.',
            'pricing_ask' => 'Tanya paket ini',
            'pricing_ask_msg' => 'Jelaskan paket :name dan apa yang saya dapatkan.',
            'popular' => 'Paling populer',
            'team_eyebrow' => 'Tim',
            'team_title' => 'Dipimpin dari Jepang dan Indonesia.',
            'values_title' => 'Nilai yang kami pegang',
            'filter_all' => 'Semua',
            'industry_hospitality' => 'Hospitality', 'industry_technology' => 'Teknologi', 'industry_creative' => 'Agensi kreatif',
            'industry_energy' => 'Energi', 'industry_facility' => 'Manajemen gedung', 'industry_tourism' => 'Pariwisata',
            'industry_automotive' => 'Otomotif', 'industry_community' => 'Komunitas', 'industry_restaurant' => 'Restoran',
            'industry_beauty' => 'Kecantikan', 'industry_internal' => 'Internal',
            'footer_services' => 'Layanan', 'footer_company' => 'Perusahaan', 'footer_contact' => 'Kontak',
            'footer_main_site' => 'Website utama FTS', 'footer_hours' => 'Senin–Jumat, 09.00–18.00 WIB',
            'ask_aya' => 'Tanya Aya',
            'voice_on' => 'Suara aktif — klik untuk mematikan',
            'voice_off' => 'Suara mati — klik untuk mengaktifkan',
            'voice_unsupported' => 'Browser ini tidak mendukung suara.',
            'nudge_general' => 'Masih lihat-lihat? Saya bisa bantu cari layanan yang cocok untuk bisnis Anda 😊',
            'nudge_services' => 'Butuh bantuan memilih layanan? Ceritakan jenis bisnis Anda, saya rekomendasikan yang paling pas.',
            'nudge_projects' => 'Mau lihat contoh proyek yang mirip bisnis Anda? Sebutkan industrinya, saya carikan.',
            'nudge_pricing' => 'Ada pertanyaan soal harga? Saya bisa jelaskan paket mana yang cocok untuk kebutuhan Anda.',
            'nudge_about' => 'Ingin tahu lebih jauh tentang tim FTS atau cara kami bekerja? Tanyakan saja.',
            'nudge_contact' => 'Siap konsultasi gratis? Sebutkan nama dan nomor WhatsApp Anda, tim FTS akan menghubungi.',
            'ai_disclosure' => 'Anda berbicara dengan AI. Tim manusia kami bisa bergabung kapan saja.',
        ];
    }

    /**
     * @return array<string, string>
     */
    private static function english(): array
    {
        return [
            'nav_services' => 'Services',
            'nav_projects' => 'Projects',
            'nav_how' => 'How it works',
            'nav_about' => 'About',
            'nav_contact' => 'Contact',
            'talk_to_staff' => 'Talk to AI Staff',
            'studio_companion' => 'Your ideas. Your AI companion.',
            'studio_explore' => 'Discover what we build',
            'studio_welcome' => 'Hi, I’m :name.',
            'studio_chat' => 'A space for your next idea',
            'studio_expand' => 'Expand conversation',
            'hero_eyebrow' => 'Welcome to FTS AI Studio',
            'hero_title' => 'Big ideas start',
            'hero_title_accent' => 'with a conversation.',
            'hero_intro' => 'Meet :name, your AI companion at FTS. Explore solutions, find inspiration, and bring your next business idea to life.',
            'hero_try' => 'Try asking',
            'hero_greeting' => "Hi! I'm :name 👋 How can I help?",
            'hero_markets' => 'Serving businesses in Indonesia & Japan',
            'q_about' => 'What is FTS?',
            'q_about_msg' => 'Hi, what is FTS and what does the company do?',
            'q_services' => 'Your services',
            'q_services_msg' => 'What services does FTS offer?',
            'q_projects' => 'Show projects',
            'q_projects_msg' => 'Can you show me some projects FTS has built?',
            'q_ai_website' => 'What is an AI Website?',
            'q_ai_website_msg' => 'What is an AI Website, and how is it different from a normal chatbot?',
            'q_price' => 'How much?',
            'q_price_msg' => 'How much does an AI Website cost?',
            'q_consult' => 'Book a consultation',
            'q_consult_msg' => "I'm interested and would like a free consultation.",
            'services_eyebrow' => 'Services',
            'services_title' => 'Technology that goes to work for your business.',
            'services_sub' => 'Web development, AI automation, offshore development and the AI Website — built with Japanese quality standards and Indonesian market insight.',
            'from' => 'From',
            'by_quotation' => 'Priced to your scope',
            'ask_about_service' => 'Ask AI Staff',
            'ask_service_msg' => 'Tell me more about :name.',
            'featured' => 'Featured',
            'how_eyebrow' => 'Not just a chatbot',
            'how_title' => 'An AI staff member that actually works inside your website.',
            'how_1_title' => 'Knows your business',
            'how_1_body' => "Answers from your company's approved knowledge base — never guesses.",
            'how_2_title' => 'Shows real data',
            'how_2_body' => 'Pulls services, prices, photos and projects straight from your database.',
            'how_3_title' => 'Gets things done',
            'how_3_body' => 'Records consultation, demo, quotation or reservation requests for your team.',
            'how_4_title' => 'Knows when to call a human',
            'how_4_body' => 'Hands the conversation to your team with a ready-to-act summary.',
            'projects_eyebrow' => 'Projects & solutions',
            'projects_title' => 'Already running, not just a concept.',
            'projects_sub' => 'Websites, platforms and AI solutions we have built for clients in Indonesia, Japan and Thailand.',
            'ask_about_project' => 'Ask about this project',
            'ask_project_msg' => 'Tell me about the :name project.',
            'projects_more' => ':count projects in our portfolio — ask for the examples most relevant to your business.',
            'visit' => 'Visit',
            'status_live' => 'Live',
            'status_pilot' => 'Pilot',
            'status_demo' => 'Demo',
            'status_in_development' => 'In development',
            'about_eyebrow' => 'About FTS',
            'process_title' => 'How we work',
            'faq_title' => 'Frequently asked',
            'faq_more' => 'Something else? Ask the AI Staff directly.',
            'cta_title' => 'Ready for an AI Staff of your own?',
            'cta_body' => 'Tell us about your business. :name will note what you need and the FTS team will get in touch.',
            'cta_button' => 'Start a free consultation',
            'footer_note' => 'This website runs on the AI Website built by FTS.',
            'staff_role' => 'AI Staff · FTS',
            'staff_online' => 'Online',
            'chat_placeholder' => 'Type your question…',
            'chat_send' => 'Send',
            'chat_intro' => "Hi! I'm :name, the AI Staff at FTS. I can explain our services, show you our projects, or help you start a consultation. How can I help?",
            'thinking' => ':name is typing…',
            'handed_over' => 'The FTS team has been notified and will join this conversation.',
            'waiting_for_staff' => 'Your message has been passed to the FTS team. Please hold on a moment.',
            'staff_label' => 'FTS team',
            'view_details' => 'View details',
            'see_projects' => 'See example projects',
            'lead_received' => 'Request received',
            'lead_followup' => 'The FTS team will contact you shortly.',
            'lead_type_consultation' => 'Consultation',
            'lead_type_demo' => 'Demo',
            'lead_type_quotation' => 'Quotation',
            'reference' => 'Reference',
            'features' => 'Key features',
            'pricing' => 'Pricing',
            'open_menu' => 'Open menu',
            'close' => 'Close',
            'new_chat' => 'New conversation',
            'connection_error' => 'The AI Staff could not connect. Reload the page to try again.',
            'error_generic' => 'Sorry, the AI Staff is unavailable right now. Please try again in a moment.',
            'stat_projects' => 'projects delivered',
            'stat_services' => 'services',
            'stat_languages' => 'languages',
            'stat_available' => 'AI Staff on duty',
            'stat_countries' => 'countries',
            'demo_visitor' => 'I run a 40-room hotel in Bali. What can you do for me?',
            'demo_staff' => 'Of course! For a hotel, an AI Website works as a virtual front desk: guests check rooms and prices, then book. Here is one already running 👇',
            'demo_card_title' => 'Hotel AI Website V1',
            'demo_card_sub' => 'Virtual front desk · reservations · 3 languages',
            'pricing_eyebrow' => 'Pricing',
            'pricing_title' => 'Transparent pricing, no hidden fees.',
            'pricing_sub' => 'Plans with public prices are below. AI Websites, AI automation and custom projects are priced to scope — ask Aya for a quotation.',
            'pricing_ask' => 'Ask about this plan',
            'pricing_ask_msg' => 'Explain the :name plan and what I get.',
            'popular' => 'Most popular',
            'team_eyebrow' => 'Team',
            'team_title' => 'Led from Japan and Indonesia.',
            'values_title' => 'What drives us',
            'filter_all' => 'All',
            'industry_hospitality' => 'Hospitality', 'industry_technology' => 'Technology', 'industry_creative' => 'Creative agency',
            'industry_energy' => 'Energy', 'industry_facility' => 'Facility management', 'industry_tourism' => 'Tourism',
            'industry_automotive' => 'Automotive', 'industry_community' => 'Community', 'industry_restaurant' => 'Restaurant',
            'industry_beauty' => 'Beauty', 'industry_internal' => 'Internal',
            'footer_services' => 'Services', 'footer_company' => 'Company', 'footer_contact' => 'Contact',
            'footer_main_site' => 'FTS main website', 'footer_hours' => 'Mon–Fri, 9 AM–6 PM (WIB)',
            'ask_aya' => 'Ask Aya',
            'voice_on' => 'Voice on — click to mute',
            'voice_off' => 'Voice off — click to enable',
            'voice_unsupported' => 'This browser does not support voice.',
            'nudge_general' => 'Still browsing? I can help you find the right service for your business 😊',
            'nudge_services' => 'Need help choosing a service? Tell me your business type and I will recommend the best fit.',
            'nudge_projects' => 'Want to see projects similar to your business? Name the industry and I will find them.',
            'nudge_pricing' => 'Questions about pricing? I can explain which plan fits your needs.',
            'nudge_about' => 'Curious about the FTS team or how we work? Just ask.',
            'nudge_contact' => 'Ready for a free consultation? Share your name and WhatsApp number and the FTS team will reach out.',
            'ai_disclosure' => 'You are chatting with an AI. A human team member can join at any time.',
        ];
    }

    /**
     * @return array<string, string>
     */
    private static function japanese(): array
    {
        return [
            'nav_services' => 'サービス',
            'nav_projects' => '実績',
            'nav_how' => '仕組み',
            'nav_about' => '会社概要',
            'nav_contact' => 'お問い合わせ',
            'talk_to_staff' => 'AIスタッフに相談',
            'studio_companion' => 'アイデアに寄り添うAIパートナー',
            'studio_explore' => 'FTSのソリューションを見る',
            'studio_welcome' => 'こんにちは、:nameです。',
            'studio_chat' => '次のアイデアが生まれる場所',
            'studio_expand' => '会話を拡大する',
            'hero_eyebrow' => 'FTS AI Studioへようこそ',
            'hero_title' => '大きなアイデアは、',
            'hero_title_accent' => '会話から始まる。',
            'hero_intro' => 'FTSのAIパートナー、:nameです。ソリューションを探し、ヒントを見つけ、ビジネスのアイデアを一緒に形にしましょう。',
            'hero_try' => '質問してみてください',
            'hero_greeting' => 'こんにちは！:nameです 👋 何かお手伝いしましょうか？',
            'hero_markets' => 'インドネシアと日本のビジネスをサポート',
            'q_about' => 'FTSとは？',
            'q_about_msg' => 'こんにちは。FTSはどんな会社ですか？',
            'q_services' => 'サービス内容',
            'q_services_msg' => 'FTSはどんなサービスを提供していますか？',
            'q_projects' => '実績を見る',
            'q_projects_msg' => 'FTSがこれまでに手がけたプロジェクトを見せてください。',
            'q_ai_website' => 'AIウェブサイトとは？',
            'q_ai_website_msg' => 'AIウェブサイトとは何ですか？普通のチャットボットと何が違いますか？',
            'q_price' => '料金は？',
            'q_price_msg' => 'AIウェブサイトの料金はいくらですか？',
            'q_consult' => '無料相談を予約',
            'q_consult_msg' => '興味があるので、無料相談をお願いしたいです。',
            'services_eyebrow' => 'サービス',
            'services_title' => 'ビジネスのために、すぐに働くテクノロジー。',
            'services_sub' => 'ウェブ開発、AI自動化、オフショア開発、そしてAIウェブサイト。日本の品質基準とインドネシア市場への理解で提供します。',
            'from' => '',
            'by_quotation' => 'ご要望に応じてお見積り',
            'ask_about_service' => 'AIスタッフに聞く',
            'ask_service_msg' => ':nameについて詳しく教えてください。',
            'featured' => 'おすすめ',
            'how_eyebrow' => 'ただのチャットボットではありません',
            'how_title' => 'ウェブサイトの中で本当に働くAIスタッフ。',
            'how_1_title' => '御社のことを理解',
            'how_1_body' => '会社が承認したナレッジベースから回答し、推測はしません。',
            'how_2_title' => '実際のデータを表示',
            'how_2_body' => 'サービス、料金、写真、実績をデータベースから直接表示します。',
            'how_3_title' => '業務をこなす',
            'how_3_body' => '相談・デモ・見積り・予約のリクエストをチームのために記録します。',
            'how_4_title' => '人に引き継ぐ判断も',
            'how_4_body' => '要約を添えて、スムーズにスタッフへ会話を引き継ぎます。',
            'projects_eyebrow' => '実績・ソリューション',
            'projects_title' => 'コンセプトではなく、すでに稼働中。',
            'projects_sub' => 'インドネシア・日本・タイのお客様向けに構築したウェブサイト、プラットフォーム、AIソリューション。',
            'ask_about_project' => 'このプロジェクトについて聞く',
            'ask_project_msg' => '「:name」について教えてください。',
            'projects_more' => '実績は全:count件。御社に近い事例をAIスタッフにお尋ねください。',
            'visit' => '見る',
            'status_live' => '稼働中',
            'status_pilot' => 'パイロット',
            'status_demo' => 'デモ',
            'status_in_development' => '開発中',
            'about_eyebrow' => 'FTSについて',
            'process_title' => '進め方',
            'faq_title' => 'よくあるご質問',
            'faq_more' => 'その他のご質問は、AIスタッフに直接どうぞ。',
            'cta_title' => '御社専用のAIスタッフを持ちませんか？',
            'cta_body' => '御社のビジネスについてお聞かせください。:nameがご要望を記録し、FTSチームからご連絡いたします。',
            'cta_button' => '無料相談を始める',
            'footer_note' => 'このウェブサイトはFTSのAIウェブサイトで運営されています。',
            'staff_role' => 'AIスタッフ · FTS',
            'staff_online' => 'オンライン',
            'chat_placeholder' => 'ご質問を入力してください…',
            'chat_send' => '送信',
            'chat_intro' => 'こんにちは！FTSのAIスタッフ、:nameです。サービスのご説明、実績のご紹介、ご相談の受付などをお手伝いします。何でもお気軽にどうぞ。',
            'thinking' => ':nameが入力中…',
            'handed_over' => 'FTSチームに通知しました。まもなく担当者が参加します。',
            'waiting_for_staff' => 'メッセージをFTSチームにお伝えしました。少々お待ちください。',
            'staff_label' => 'FTSチーム',
            'view_details' => '詳細を見る',
            'see_projects' => '事例を見る',
            'lead_received' => 'リクエストを受け付けました',
            'lead_followup' => 'FTSチームより折り返しご連絡いたします。',
            'lead_type_consultation' => 'ご相談',
            'lead_type_demo' => 'デモ',
            'lead_type_quotation' => 'お見積り',
            'reference' => '受付番号',
            'features' => '主な機能',
            'pricing' => '料金',
            'open_menu' => 'メニューを開く',
            'close' => '閉じる',
            'new_chat' => '新しい会話',
            'connection_error' => 'AIスタッフに接続できませんでした。ページを再読み込みしてください。',
            'error_generic' => '申し訳ありません。AIスタッフは現在ご利用いただけません。しばらくしてからお試しください。',
            'stat_projects' => '件の実績',
            'stat_services' => 'つのサービス',
            'stat_languages' => 'か国語',
            'stat_available' => 'AIスタッフ対応',
            'stat_countries' => 'か国',
            'demo_visitor' => 'バリ島で40室のホテルを経営しています。何ができますか？',
            'demo_staff' => 'もちろんです！ホテルならAIウェブサイトがバーチャルフロントになります。お客様が客室と料金を確認し、そのまま予約できます。稼働中の事例はこちら 👇',
            'demo_card_title' => 'ホテルAIウェブサイト V1',
            'demo_card_sub' => 'バーチャルフロント · 予約 · 3か国語',
            'pricing_eyebrow' => '料金',
            'pricing_title' => '追加費用のない、透明な料金。',
            'pricing_sub' => '公開料金のあるプランは以下の通りです。AIウェブサイト、AI自動化、個別案件は範囲に応じてお見積りします。Ayaにお尋ねください。',
            'pricing_ask' => 'このプランについて聞く',
            'pricing_ask_msg' => '「:name」プランの内容を教えてください。',
            'popular' => '人気No.1',
            'team_eyebrow' => 'チーム',
            'team_title' => '日本とインドネシアから率いるチーム。',
            'values_title' => '大切にしている価値観',
            'filter_all' => 'すべて',
            'industry_hospitality' => 'ホスピタリティ', 'industry_technology' => 'テクノロジー', 'industry_creative' => 'クリエイティブ',
            'industry_energy' => 'エネルギー', 'industry_facility' => 'ビル管理', 'industry_tourism' => '観光',
            'industry_automotive' => '自動車', 'industry_community' => 'コミュニティ', 'industry_restaurant' => '飲食',
            'industry_beauty' => '美容', 'industry_internal' => '社内',
            'footer_services' => 'サービス', 'footer_company' => '会社', 'footer_contact' => 'お問い合わせ',
            'footer_main_site' => 'FTS公式サイト', 'footer_hours' => '月〜金 9:00〜18:00（ジャカルタ時間）',
            'ask_aya' => 'Ayaに聞く',
            'voice_on' => '音声オン — クリックでオフ',
            'voice_off' => '音声オフ — クリックでオン',
            'voice_unsupported' => 'このブラウザは音声に対応していません。',
            'nudge_general' => 'ご覧いただきありがとうございます。御社に合うサービス探しをお手伝いできます 😊',
            'nudge_services' => 'サービス選びでお困りですか？業種を教えていただければ、最適なものをご提案します。',
            'nudge_projects' => '御社に近い事例をご覧になりますか？業種を教えてください。お探しします。',
            'nudge_pricing' => '料金についてのご質問はありますか？ご要望に合うプランをご説明します。',
            'nudge_about' => 'FTSのチームや進め方について、気になることがあればお尋ねください。',
            'nudge_contact' => '無料相談をご希望ですか？お名前とWhatsApp番号をお知らせいただければ、FTSチームからご連絡します。',
            'ai_disclosure' => 'AIとチャットしています。担当者がいつでも参加できます。',
        ];
    }
}
